### PR TITLE
Vowel Adder

### PR DESCRIPTION
**Pull request by kcdark**
Added consonant excluder for first move as a temp fix until piece swapping is available.
Small, but helpful if you have no vowels on the first play.

### CODE REVIEW

**Comment by olumidesan** [comment]
Hi, @kcdark, I'm not sure what you did. Can you explain?

**Comment by kcdark** [comment]
If you did not get any vowels on the first play you would have to start over the game by refreshing it. This way as a temporary fix it provides a vowel on the first move just to make sure you can play something and start the game.


def not_all_consonants(pieces):

"""

Prevents all consonants

"""

while not_all_consonants(pieces): pieces = get_pieces(amount, room_id)

**Comment by olumidesan** [comment]
Oh, rad. Thanks. Makes a lot of sense. Seems you've closed the PR already. Do you want to re-open it, or I just add it myself?

**Comment by kcdark** [comment]
Sorry, I had a issue and had to close it. I will pull a new one.
Just opened it. Hope it fares well.

**Pull request closed without merging**
